name: Continuous Integration

on:
  push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Start MySQL service using Docker Compose
      run: |
        docker-compose --file .github/workflows/docker-compose.yml up -d

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and build frontend
      working-directory: ./client
      run: |
        npm install
    - name: Run frontend tests
      working-directory: ./client
      run: npm test

    - name: Set up MySQL connection
      run: |
        echo "MYSQL_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "MYSQL_PORT=${{ job.services.mysql.ports['5000'] }}" >> $GITHUB_ENV
        echo "MYSQL_USER=root" >> $GITHUB_ENV
        echo "MYSQL_PASSWORD=" >> $GITHUB_ENV
        echo "MYSQL_DATABASE=croma" >> $GITHUB_ENV

    - name: Install dependencies and build backend
      working-directory: ./server
      run: |
        npm install
    - name: Run backend tests
      working-directory: ./server
      run: npm test
