version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: croma
    ports:
      - "5000:3306"
    healthcheck:
      test: "mysqladmin ping"
      interval: 10s
      timeout: 5s
      retries: 3
    command: --skip-grant-tables
